const {chromium}=require('C:/Users/64177/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:960}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:5173',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
 await page.getByRole('button',{name:'开启音乐'}).click();
 console.log('sound enabled',await page.locator('video').evaluate(v=>!v.muted));
 await page.getByRole('button',{name:'关闭音乐'}).click();
 console.log('sound disabled',await page.locator('video').evaluate(v=>v.muted));
 await page.getByRole('button',{name:'开启音乐'}).click();
 console.log('loop disabled',await page.locator('video').evaluate(v=>!v.loop));
 console.log('end message hidden during playback',await page.locator('.hero-end-message').count()===0);
 await page.locator('video').evaluate(v=>{v.currentTime=40});
 await page.waitForTimeout(1000);
 console.log('audio visualization',await page.locator('.audio-line').evaluate(c=>{const ctx=c.getContext('2d'),a=ctx.getImageData(0,0,c.width,c.height).data;let min=c.height,max=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(a[(y*c.width+x)*4+3]>100){min=Math.min(min,y);max=Math.max(max,y)}return {width:c.width,waveHeight:max-min,responds:max-min>4}}));
 await page.locator('video').evaluate(v=>{v.currentTime=v.duration-.2});
 await page.getByRole('button',{name:'再播放一次'}).waitFor();
 console.log('ended stopped',await page.locator('video').evaluate(v=>v.ended&&v.paused));
 console.log('end message centered and blue',await page.locator('.hero-end-message').evaluate(el=>{const r=el.getBoundingClientRect(),h=document.querySelector('.hero').getBoundingClientRect();return {centered:Math.abs(r.x+r.width/2-(h.x+h.width/2))<2&&Math.abs(r.y+r.height/2-(h.y+h.height/2))<2,color:getComputedStyle(el).color}}));
 await page.screenshot({path:'preview-video-ended.png'});
 await page.getByRole('button',{name:'再播放一次'}).click();
 console.log('replay from start with sound',await page.locator('video').evaluate(v=>v.currentTime<2&&!v.paused&&!v.muted));
 console.log('end message hidden on replay',await page.locator('.hero-end-message').count()===0);
 await page.screenshot({path:'preview-desktop.png'});
 console.log('desktop',await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,sections:document.querySelectorAll('main>section').length,videoReady:document.querySelector('video').readyState,videoPaused:document.querySelector('video').paused,images:[...document.images].every(i=>i.complete&&i.naturalWidth>0)})));
 await page.getByRole('button',{name:'暂停背景视频'}).click();
 console.log('video pause',await page.locator('video').evaluate(v=>v.paused));
 await page.getByRole('button',{name:'查看中央管理与决策支持'}).click();
 console.log('dialog',await page.locator('dialog').evaluate(d=>d.open));
 await page.keyboard.press('Escape');
 console.log('dialog closes',await page.locator('dialog').evaluate(d=>!d.open));
 console.log('glow cards',await page.locator('.border-glow-card').count());
 const glow=page.locator('.project-glow').first();await glow.scrollIntoViewIfNeeded();await glow.hover({position:{x:8,y:40}});
 console.log('glow follows pointer',await glow.evaluate(el=>Number(el.style.getPropertyValue('--edge-proximity'))>0&&el.style.getPropertyValue('--cursor-angle').includes('deg')));
 await page.locator('#work').scrollIntoViewIfNeeded();await page.waitForTimeout(800);await page.screenshot({path:'preview-projects.png'});
 console.log('floating nav after hero',await page.locator('header.nav').evaluate(n=>({fixed:getComputedStyle(n).position==='fixed',top:n.getBoundingClientRect().top})));
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(100);
 console.log('nav returns to hero',await page.locator('header.nav').evaluate(n=>getComputedStyle(n).position==='absolute'));
 console.log('resume', (await page.request.get('http://localhost:5173/resume.pdf')).status());
 await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:5173');await page.waitForTimeout(600);
 await page.getByRole('button',{name:'切换导航'}).click();await page.getByRole('link',{name:'关于我',exact:true}).click();
 console.log('mobile',await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,hash:location.hash})));await page.screenshot({path:'preview-mobile.png'});
 console.log('runtime errors',errors);await browser.close();if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
